/*
    TicTacToeHumanPlayer.cpp
    

*/
//----------------------------------------
//TicTacToeHumanPlayer.cpp generated by cbtek on 07-12-2017 at 03:53:42 PM
//----------------------------------------
#include "TicTacToeHumanPlayer.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {
namespace player_types {


TicTacToeHumanPlayer::TicTacToeHumanPlayer()
{

}

TicTacToePlayerType TicTacToeHumanPlayer::getPlayerType() const
{
    return TicTacToePlayerType::Human;
}

void TicTacToeHumanPlayer::play(TicTacToeBoard &currentBoard)
{

}

TicTacToeHumanPlayer::~TicTacToeHumanPlayer()
{

}

}}}}//end namespace


