/*
    TicTacToeHumanPlayer.cpp
    

*/
//----------------------------------------
//TicTacToeHumanPlayer.cpp generated by cbtek on 07-12-2017 at 03:53:42 PM
//----------------------------------------
#include "TicTacToeHumanPlayer.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {
namespace players {


TicTacToeHumanPlayer::TicTacToeHumanPlayer()
{

}

TicTacToePlayerType TicTacToeHumanPlayer::getPlayerType() const
{
    return TicTacToePlayerType::Human;
}

TicTacToePlayResultType TicTacToeHumanPlayer::play(int &rowPlayed,
                                                   int &columnPlayed,
                                                   const TicTacToeBoard &currentBoard)
{
    return TicTacToePlayResultType::RandomPlay;
}

TicTacToeHumanPlayer::~TicTacToeHumanPlayer()
{

}

}}}}//end namespace


