/*
    TicTacToeTestComputerPlayer.cpp
    

*/
//----------------------------------------
//TicTacToeTestComputerPlayer.cpp generated by cbtek on 07-14-2017 at 04:55:41 PM
//----------------------------------------
#include "TicTacToeTestComputerPlayer.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {
namespace players {


TicTacToeTestComputerPlayer::TicTacToeTestComputerPlayer()
{

}

TicTacToePlayerType TicTacToeTestComputerPlayer::getPlayerType() const
{

}

TicTacToePlayResultType TicTacToeTestComputerPlayer::play(int &rowPlayed,
                                                          int &columnPlayed,
                                                          const TicTacToeBoard &currentBoard)
{

}

TicTacToeTestComputerPlayer::~TicTacToeTestComputerPlayer()
{

}




}}}}//end namespace


