/*
    UIWebcamMainWindow.cpp
    

*/
//UIWebcamMainWindow.cpp generated by cbtek on 07-12-2017 at 05:15:29 PM

#include "UIWebcamMainWindow.h"
#include "ui_UIWebcamMainWindow.h"

#include <QDebug>

namespace pf_projects {
namespace products {
namespace webcam {


UIWebcamMainWindow::UIWebcamMainWindow(QWidget *parent) :
    QMainWindow(parent),
    m_ui(new Ui_UIWebcamMainWindow)
{
    m_ui->setupUi(this);

}

UIWebcamMainWindow::~UIWebcamMainWindow()
{
    delete m_ui;
}
}}}//end namespace

