/*
    TicTacToePlayerFactory.cpp
*/
//----------------------------------------
//TicTacToePlayerFactory.cpp generated by cbtek on 07-14-2017 at 01:51:14 AM
//----------------------------------------

#include "TicTacToePlayerFactory.h"

#include "players/TicTacToeBasicComputerPlayer.h"
#include "players/TicTacToeHumanPlayer.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {

TicTacToePlayerPtr TicTacToePlayerFactory::create(const std::string& playerName,
                                                  TicTacToePlayerClass playerClass,
                                                  TicTacToePlayerType playerType)
{
    TicTacToePlayerPtr player;
    switch(playerType)
    {

        case TicTacToePlayerType::Human:
        {
            player = TicTacToePlayerPtr(new players::TicTacToeHumanPlayer);
            TicTacToePlayerImpl * impl = dynamic_cast<TicTacToePlayerImpl*>(player.get());
            if (impl)
            {
                impl->setPlayerClass(playerClass);
                impl->setPlayerName(playerName);
            }
            break;
        }       
        case TicTacToePlayerType::BasicComputer:
        {
            player = TicTacToePlayerPtr(new players::TicTacToeBasicComputerPlayer());
            TicTacToePlayerImpl * impl = dynamic_cast<TicTacToePlayerImpl*>(player.get());
            if (impl)
            {
                impl->setPlayerClass(playerClass);
                impl->setPlayerName(playerName);
            }
            break;
        }
        default: break;
    }
    return player;
}
}}}//end namespace


