/*
    TicTacToePlayerFactory.cpp
    

*/
//----------------------------------------
//TicTacToePlayerFactory.cpp generated by cbtek on 07-14-2017 at 01:51:14 AM
//----------------------------------------

#include "TicTacToePlayerFactory.h"

#include "player_types/TicTacToeComputerPlayer.h"
#include "player_types/TicTacToeHumanPlayer.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {

TicTacToePlayerPtr TicTacToePlayerFactory::create(const std::string& playerName,
                                                  TicTacToePlayerClass playerClass,
                                                  TicTacToePlayerType playerType)
{
    TicTacToePlayerPtr player;
    switch(playerType)
    {
        case TicTacToePlayerType::Human:
        {
            player = TicTacToePlayerPtr(new player_types::TicTacToeHumanPlayer());
            TicTacToePlayerImpl * impl = dynamic_cast<TicTacToePlayerImpl*>(player.get());
            if (impl)
            {
                impl->setPlayerClass(playerClass);
                impl->setPlayerName(playerName);
            }
            break;
        }
        case TicTacToePlayerType::Computer:
        {
            player = TicTacToePlayerPtr(new player_types::TicTacToeComputerPlayer());
            TicTacToePlayerImpl * impl = dynamic_cast<TicTacToePlayerImpl*>(player.get());
            if (impl)
            {
                impl->setPlayerClass(playerClass);
                impl->setPlayerName(playerName);
            }
            break;
        }
        default: break;
    }
    return player;
}
}}}//end namespace


