/*
    TicTacToePlayerImpl.cpp
    

*/
//----------------------------------------
//TicTacToePlayerImpl.cpp generated by cbtek on 07-12-2017 at 03:52:24 PM
//----------------------------------------
#include "TicTacToePlayerImpl.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {


TicTacToePlayerImpl::TicTacToePlayerImpl()
{

}

TicTacToePlayerClass TicTacToePlayerImpl::getPlayerClass() const
{
    return m_class;
}

void TicTacToePlayerImpl::setPlayerClass(TicTacToePlayerClass playerClass)
{
    m_class = playerClass;
}

std::string TicTacToePlayerImpl::getPlayerName() const
{
    return m_name;
}

void TicTacToePlayerImpl::setPlayerName(const std::string &name)
{
    m_name = name;
}

TicTacToePlayerImpl::~TicTacToePlayerImpl()
{

}
}}}//end namespace


