/*
    UITicTacToeBoardView.cpp
    

*/
//UITicTacToeBoardView.cpp generated by cbtek on 07-13-2017 at 10:27:11 PM

#include "UITicTacToeBoardView.h"

#include <QColor>
#include <QPainter>
#include <QTimer>

#include <iostream>

namespace pf_projects {
namespace products {
namespace tic_tac_toe {


UITicTacToeBoardView::UITicTacToeBoardView()
{    
    onInitialize();
}

void UITicTacToeBoardView::placeX(int row, int column)
{
    place(row,column,TicTacToeTokenType::X);
}

void UITicTacToeBoardView::placeO(int row, int column)
{
    place(row,column,TicTacToeTokenType::O);
}

void UITicTacToeBoardView::reset()
{    
    m_tokens.clear();
    m_tokens.resize(9);
}

void UITicTacToeBoardView::updateBoardMouseClick(int mousePosX, int mousePosY)
{
    for (size_t r = 0; r < 3; ++r)
    {
        for (size_t c = 0; c < 3; ++c)
        {
            size_t index = TicTacToeUtils::getIndex(r,c);
            UITicTacToeToken token = m_tokens[index];
            QRect rect(token.x,token.y,token.w,token.h);
            if (rect.contains(mousePosX, mousePosY) &&
                token.playerClass == TicTacToePlayerClass::NoPlayer)
            {
                emit humanPlayRequested(token.row,token.column);
                return ;
            }
        }
    }
}

void UITicTacToeBoardView::updateBoardMousePosition(int mousePosX, int mousePosY)
{
    m_mouseX = mousePosX;
    m_mouseY = mousePosY;
    emit repaintRequested();
}

void UITicTacToeBoardView::updateBoardSize(int width, int height)
{
    if (m_tokens.size() == 0)
    {
        reset();
    }
    m_width = width;
    m_height = height;
    m_imgBuffer = QImage(width,height,QImage::Format_ARGB32);

    int sizeW = m_width / 3.0;
    int sizeH = m_height / 3.0;

    for (size_t r = 0; r < 3; ++r)
    {
        for (size_t c = 0; c < 3; ++c)
        {
            size_t index = TicTacToeUtils::getIndex(r,c);
            m_tokens[index].row = r;
            m_tokens[index].column = c;
            m_tokens[index].x = c * sizeW;
            m_tokens[index].y = r * sizeH;
            m_tokens[index].w = sizeW;
            m_tokens[index].h = sizeH;
        }
    }
    emit repaintRequested();
}

void UITicTacToeBoardView::createPlayerImages()
{
    m_imgX.load(":/imgX.png");
    m_imgO.load(":/imgO.png");
}

void UITicTacToeBoardView::place(int row, int column, TicTacToeTokenType tokenType)
{
    TicTacToePlayerClass playerClass = (tokenType == TicTacToeTokenType::X ? TicTacToePlayerClass::Player1 : TicTacToePlayerClass::Player2);
    size_t index = TicTacToeUtils::getIndex(row,column);
    m_tokens[index].playerClass = playerClass;
    m_tokens[index].tokenType = tokenType;
    emit repaintRequested();
}

void UITicTacToeBoardView::drawBoard(const QRect &drawRectangle, QPainter &g)
{
    QPainter bufferG(&m_imgBuffer);
    bufferG.fillRect(0,0,m_width,m_height,Qt::red);
    for (size_t r = 0; r < 3; ++r)
    {
        for (size_t c = 0; c < 3; ++c)
        {
            size_t index = TicTacToeUtils::getIndex(r,c);
            UITicTacToeToken token = m_tokens[index];
            QRect rect (token.x,token.y,token.w,token.h);

            if (token.playerClass == TicTacToePlayerClass::NoPlayer)
            {
                bufferG.fillRect(rect,QColor(255,255,255));
            }
            else if (token.playerClass == TicTacToePlayerClass::Player1)
            {
                bufferG.fillRect(rect,QColor(127,255,127));
            }
            else if (token.playerClass == TicTacToePlayerClass::Player2)
            {
                bufferG.fillRect(rect,QColor(255,127,127));
            }
            if (rect.contains(QPoint(m_mouseX,m_mouseY)))
            {
                bufferG.fillRect(rect,Qt::black);
            }
            if (m_tokens[index].tokenType == TicTacToeTokenType::X)
            {
                bufferG.drawImage(rect,m_imgX);
            }
            else if (m_tokens[index].tokenType == TicTacToeTokenType::O)
            {
                bufferG.drawImage(rect,m_imgO);
            }            

        }
    }
    g.drawImage(drawRectangle,m_imgBuffer);
}

void UITicTacToeBoardView::onInitialize()
{
    createPlayerImages();
    reset();
}

UITicTacToeBoardView::~UITicTacToeBoardView()
{    
}


}}}//end namespace

