/*
    UITicTacToeWindow.cpp
    

*/
//UITicTacToeWindow.cpp generated by cbtek on 07-17-2017 at 03:15:25 AM

#include "UITicTacToeWindow.h"
#include "ui_UITicTacToeWindow.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {


UITicTacToeWindow::UITicTacToeWindow(QWidget *parent) :
    QMainWindow(parent),
    m_ui(new Ui_UITicTacToeWindow)
{
    m_ui->setupUi(this);
    m_ptrBoardMain = new UITicTacToeBoardMain;
    m_ui->m_frmMain->layout()->addWidget(m_ptrBoardMain);
}

UITicTacToeWindow::~UITicTacToeWindow()
{
    delete m_ui;
}
}}}//end namespace

