/*
    UITicTacToeMainWindow.cpp
    

*/
//UITicTacToeMainWindow.cpp generated by cbtek on 07-12-2017 at 02:23:37 AM

#include "UITicTacToeMainWindow.h"
#include "ui_UITicTacToeMainWindow.h"
#include "UITicTacToeBoard.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {


UITicTacToeMainWindow::UITicTacToeMainWindow(QWidget *parent) :
    QMainWindow(parent),
    m_ui(new Ui_UITicTacToeMainWindow)
{
    m_ui->setupUi(this);
    m_ui->m_lytMain->addWidget(new UITicTacToeBoard);
}


UITicTacToeMainWindow::~UITicTacToeMainWindow()
{
    delete m_ui;
}

void UITicTacToeMainWindow::resizeEvent(QResizeEvent *event)
{

}
}}}//end namespace

