/*
    UITicTacToeBoardMain.cpp
    

*/
//UITicTacToeBoardMain.cpp generated by cbtek on 07-12-2017 at 02:23:37 AM

#include "UITicTacToeBoardMain.h"
#include "ui_UITicTacToeBoardMain.h"

#include <QPainter>

using namespace cbtek::common::utility;

using namespace pf_projects::products::qt_widget_animation_library;

namespace pf_projects {
namespace products {
namespace tic_tac_toe {

const static double c_X_POS_PERCENTAGE = 272 / 1024.0;
const static double c_Y_POS_PERCENTAGE = 78 / 768.0;
const static double c_WIDTH_AMOUNT = 480;
const static double c_HEIGHT_AMOUNT = 480;

UITicTacToeBoardMain::UITicTacToeBoardMain(QWidget *parent) :
    QWidget(parent),
    m_ui(new Ui_UITicTacToeBoardMain)
{
    m_ui->setupUi(this);    
    m_isMousePress = false;
    m_isStaticEnabled = true;
    m_isMusicEnabled = true;
    m_intMouseX = 0;
    m_intMouseY = 0;
    m_intContentX = 0;
    m_intContentY = 0;
    m_intContentW = 0;
    m_intContentH = 0;
    m_intXScore = 0;
    m_intOScore = 0;
    m_intDScore = 0;
    m_ptrBoardView = nullptr;
    m_ptrBoardController = nullptr;

    //Load images for nuka boy
    m_imgUnderlay.load(":/imgNukaBoyBase.png");
    m_imgOverlay.load(":/imgNukaBoyOverlay.png");
    m_imgBackground.load(":/imgNukaBoyBackground.png");

    //Load audio files
    m_audTokenPlay.setSource(QUrl("qrc:/audTokenPlay.wav"));
    m_audGameOver.setSource(QUrl("qrc:/audGameOver.wav"));
    m_audThemeMusic.setMedia(QUrl("qrc:/audThemeMusic.ogg"));

    //Set audio volumes
    m_audTokenPlay.setVolume(100);
    m_audGameOver.setVolume(100);
    m_audThemeMusic.setVolume(100);

    m_ptrStaticAnimationOverlay = new UIStaticAnimation;
    m_ptrStaticAnimationOverlay->hide();
    connect(m_ptrStaticAnimationOverlay,SIGNAL(rendered(QImage)),this,SLOT(onStaticFrameRendered(QImage)));
    m_ptrStaticAnimationOverlay->start(64,255,60,32,QColor(0,255,0,26));

    this->setMouseTracking(true);
    this->startTimer(30);
    m_currentMode = TicTacToeMode::Startup;
    m_currentState.setEnter();
}

void UITicTacToeBoardMain::setStaticEnabled(bool toggle)
{
    m_isStaticEnabled = toggle;
}

void UITicTacToeBoardMain::setMusicEnabled(bool toggle)
{
    m_isMusicEnabled = toggle;
    if (toggle)
    {
        m_audThemeMusic.play();
    }
    else m_audThemeMusic.stop();
}

UITicTacToeBoardMain::~UITicTacToeBoardMain ()
{
    delete m_ui;
}

void UITicTacToeBoardMain::resizeEvent(QResizeEvent *event)
{
    m_imgBuffer = QImage(width(),height(),QImage::Format_ARGB32);
    m_intContentX = static_cast<int>(c_X_POS_PERCENTAGE * width());
    m_intContentY = static_cast<int>(c_Y_POS_PERCENTAGE * height());
    m_intContentW = (width() / 1024.0) * c_WIDTH_AMOUNT;
    m_intContentH = (height() / 768.0) * c_HEIGHT_AMOUNT;    

    if (m_ptrBoardView)
    {
        m_ptrBoardView->updateBoardSize(m_intContentW,m_intContentH);
    }
    this->update();
}

void UITicTacToeBoardMain::paintEvent(QPaintEvent *event)
{
    QWidget::paintEvent(event);
    QPainter g(this);
    g.drawImage(0,0,m_imgBuffer);

}

void UITicTacToeBoardMain::mouseMoveEvent(QMouseEvent *event)
{
    m_intMouseX = event->pos().x() - m_intContentX;
    m_intMouseY = event->pos().y() - m_intContentY;
}

void UITicTacToeBoardMain::mousePressEvent(QMouseEvent *event)
{
    m_intMouseX = event->pos().x() - m_intContentX;
    m_intMouseY = event->pos().y() - m_intContentY;
    m_isMousePress = true;
}

void UITicTacToeBoardMain::timerEvent(QTimerEvent *event)
{
    QPainter painter(&m_imgBuffer);
    QRect screenRect(0,0,m_imgBuffer.width(),m_imgBuffer.height());
    QRect contentRect(m_intContentX, m_intContentY, m_intContentW, m_intContentH);    
    painter.drawImage(screenRect, m_imgBackground);
    painter.drawImage(screenRect, m_imgUnderlay);

    switch(m_currentMode)
    {
        case TicTacToeMode::Startup:updateStartupMode(painter);break;
        case TicTacToeMode::Game:updateGameMode(painter);break;
        case TicTacToeMode::GameOver:updateGameOverMode(painter);break;        
    }

    if (m_isStaticEnabled)
    {
        painter.drawImage(contentRect,m_imgCurrentStaticFrame);
    }

    painter.drawImage(screenRect,m_imgOverlay);
    this->update();
}

void UITicTacToeBoardMain::updateStartupMode(QPainter &painter)
{
    switch(m_currentState.getType())
    {
        case StateType::Enter:
        {
            if (m_imgStartupContent.isNull())
            {
                m_imgStartupContent.load(":/imgNukaBoyLogo.png");
            }
            m_audThemeMusic.play();
            m_tmStartupTimeOut.restart();
            m_currentState.setNextStateType();
        }
        break;
        case StateType::Update:
        {
            QRect contentRect(m_intContentX, m_intContentY, m_intContentW, m_intContentH);
            painter.drawImage(contentRect,m_imgStartupContent);
            if (m_isMousePress)
            {
                m_currentState.setNextStateType();
                m_isMousePress = false;
            }
        }
        break;
        case StateType::Exit:
        {
            m_currentState.setNextStateType();
            m_currentMode = TicTacToeMode::Game;
        }
        break;
    }
}

void UITicTacToeBoardMain::updateGameMode(QPainter &painter)
{
    switch(m_currentState.getType())
    {
        case StateType::Enter:
        {            
            if (!m_ptrBoardView)
            {
                m_ptrBoardView = new UITicTacToeBoardView;
                connect(m_ptrBoardView,SIGNAL(repaintRequested()),this,SLOT(onRepaintBoard()));
            }

            if (!m_ptrBoardController)
            {
                m_ptrBoardController = new UITicTacToeBoardController(m_ptrBoardView);
                connect(m_ptrBoardController,
                        SIGNAL(playerWonRound(TicTacToePlayerClass, TicTacToePlayerType)),
                        SLOT(onPlayerWon(TicTacToePlayerClass,TicTacToePlayerType)));

                connect(m_ptrBoardController,
                        SIGNAL(playOccured(int, int, TicTacToeTokenType)),
                        this,
                        SLOT(onPlayOccured(int, int, TicTacToeTokenType)));
            }

            m_ptrBoardController->initialize();
            m_ptrBoardView->updateBoardSize(m_intContentW,m_intContentH);
            m_currentState.setUpdate();
        }
        break;
        case StateType::Update:
        {
            QRect contentRect(m_intContentX, m_intContentY, m_intContentW, m_intContentH);
            m_ptrBoardView->drawBoard(contentRect, painter);
            if (m_intMouseX >= 0 && m_intMouseY >= 0)
            {
                this->setWindowTitle("Virtual Pos: "+QString::number(m_intMouseX)+", "+QString::number(m_intMouseY));
                m_ptrBoardView->updateBoardMousePosition(m_intMouseX,m_intMouseY);
                if (m_isMousePress)
                {
                    m_ptrBoardView->updateBoardMouseClick(m_intMouseX,m_intMouseY);
                    m_isMousePress = false;
                }
            }
        }
        break;
        case StateType::Exit:
        {

        }
        break;
    }
}

void UITicTacToeBoardMain::updateGameOverMode(QPainter &painter)
{
    switch(m_currentState.getType())
    {
        case StateType::Enter:
        {
            m_currentState.setNextStateType();
            m_audGameOver.play();
        }
        break;
        case StateType::Update:
        {
            QRect contentRect(m_intContentX, m_intContentY, m_intContentW, m_intContentH);
            painter.drawImage(contentRect,m_imgGameOverContent);
            if (m_intMouseX >= 0 && m_intMouseY >= 0)
            {
                if (m_isMousePress)
                {
                    m_currentMode = TicTacToeMode::Game;
                    m_currentState.reset();
                    m_isMousePress = false;
                }
            }
        }
        break;
        case StateType::Exit:
        {
            m_currentState.setNextStateType();
        }
        break;
    }
}

void UITicTacToeBoardMain::onPlayerWon(TicTacToePlayerClass playerClass,
                                       TicTacToePlayerType playerType)
{
    if (playerClass == TicTacToePlayerClass::Player1)
    {
        ++m_intXScore;
    }
    else if (playerClass == TicTacToePlayerClass::Player2)
    {
        ++m_intOScore;
    }
    else ++m_intDScore;


    emit scoresUpdated(m_intXScore,
                       m_intOScore,
                       m_intDScore);


    m_currentMode = TicTacToeMode::GameOver;
    m_currentState.reset();
    if (playerType == TicTacToePlayerType::Human)
    {
        m_imgGameOverContent.load(":/imgWinScreen.png");
    }
    else if (playerType == TicTacToePlayerType::BasicComputer)
    {
        m_imgGameOverContent.load(":/imgLooseScreen.png");
    }
    else
    {
        m_imgGameOverContent.load(":/imgDrawScreen.png");
    }

}

void UITicTacToeBoardMain::onStaticFrameRendered(QImage frame)
{
    m_imgCurrentStaticFrame = frame;
}

void UITicTacToeBoardMain::onRepaintBoard()
{
    this->update();
}

void UITicTacToeBoardMain::onPlayOccured(int row, int column, TicTacToeTokenType tokenType)
{
    m_audTokenPlay.play();
}

}}}//end namespace

