/*
    UITicTacToeController.cpp
    

*/
//----------------------------------------
//UITicTacToeController.cpp generated by cbtek on 07-14-2017 at 01:35:37 AM
//----------------------------------------
#include "UITicTacToeController.h"

#include "TicTacToePlayerFactory.h"

namespace pf_projects {
namespace products {
namespace tic_tac_toe {


UITicTacToeController::UITicTacToeController()
{

}

void UITicTacToeController::initialize(TicTacToePlayerClass player1Class,
                                       TicTacToePlayerType player1Type,
                                       TicTacToePlayerClass player2Class,
                                       TicTacToePlayerType player2Type)
{
    m_player1 = TicTacToePlayerFactory::create("player1",player1Class,player1Type);
    m_player2 = TicTacToePlayerFactory::create("player2",player2Class,player2Type);
}

UITicTacToeController::~UITicTacToeController()
{

}




}}}//end namespace


